#!/usr/bin/env bash

set -e
if [ -z "$MSI_ENDPOINT" ]; then
  export ANSIBLE_AZURE_AUTH_SOURCE='cli'
else
  export ANSIBLE_AZURE_AUTH_SOURCE='msi'
fi

source /opt/ansible/bin/activate
ansible-playbook "$@"
deactivate
