name: Sync GitHub issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "msazure"
          ado_project: "One"
          ado_area_path: "One\\MGMT\\Compute\\Azure\ Cloud\ Shell"
          ado_iteration_path: "One\\Custom\\Azure"
          ado_wit: "Product Backlog Item"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_bypassrules: false
          log_level: 100
